### ISSUE TITLE
Export the MARC21 structure to JSON

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/qa-catalogue#45] opened 2018-01-28 11:57 UTC
Jakob Voß questioned in Twitter (https://twitter.com/nichtich/status/956810925276913664)

"is there a machine-readable list of defined MARC fields and allowed subfields and if so in which form? We're just creating such list for PICA format and I'd like to compare before defining my own little schema language."

Jonathan Rols added (https://twitter.com/johrols/status/956814998671642624):

"Ok, thanks. I would be interested in a JSON export of the schema..."

**Comment by pkiraly** [comment] 2018-01-28 12:04
A raw version is avalable at https://raw.githubusercontent.com/pkiraly/metadata-qa-marc/d11077c2a71903112b0c24225bd0f42bc1c80f1f/src/main/resources/marc-schema.json

The formatted version is displayed at
http://pkiraly.github.io/2018/01/28/marc21-in-json/

To generate the file:

```bash
./common-script
java -cp $JAR de.gwdg.metadataqa.marc.cli.MappingToJson > marc-schema.json
```
or
```bash
java -cp target/metadata-qa-marc-0.2-SNAPSHOT-jar-with-dependencies.jar de.gwdg.metadataqa.marc.cli.MappingToJson > marc-schema.json
```
(The version name will be changed in the future)

**Comment by nichtich** [comment] 2018-01-29 09:17
Thanks a lot! Some suggestions:

* Rename `URL` to `url` (all names are lowercase)
* Use an object indexed by tag (instead of an array) for quick and easy access to tags:

      { "Leader": { ... }, "001": { "label":"Control Number" } ...

* Use boolean for cardinality. I'd choose `"unique": true` for non-repeatable so it is an explicit constraint ("repetable" is no constraint but a property)

* Use an object indexed by subfield codes for subfields:

      { "subfields": { "a": { "label": ... }, ... 

* Change `indicators` from

~~~json
"indicators": {
  "ind1": { "label": "Shelving scheme" },
  "ind2": { "label": "Shelving order" }
}
~~~

to

~~~json
"indicators": [
  { "label": "Shelving scheme" },
  { "label": "Shelving order" }
]
~~~


See also my [draft of same structure for PICA+](https://github.com/gbv/PICA-Data/pull/33/files#diff-997a7337684aa4c316a8b66725a21fd5R83).

**Comment by pkiraly** [comment] 2018-01-29 09:22
Thanks for the suggestions! I can change the code according to the first 3 and maybe the 4th (I have to check it). But the last one has a problem: sometimes it happens that there are only one indicator ant it is not the first one, but the second. If we don't tell it explicitly, you can not figure it out.

**Comment by nichtich** [comment] 2018-01-29 09:27
With the 4th suggestion, the order of subfields is not preserved, is this relevant?

For the 5th, how about:

~~~json
"indicators": [
  null,
  { "label": "Shelving order" }
]
~~~

or directly attach "ind1" / "ind2" to the parent object:

~~~json
"label": "...",
"first-indcator": { "label": "Shelving scheme" },
"second-indicator": { "label": "Shelving order" }
~~~

Are "ind1" and "ind2" common abbreviations in MARC terminology?

**Comment by jorol** [comment] 2018-01-30 13:40
Thanks for your work.

Any reason why the control fields aren't marked as `non repeatable`?

```
...
"001":{"label":"Control Number"},
"003":{"label":"Control Number Identifier"},
"005":{"label":"Date and Time of Latest Transaction"},
...
"010":{"label":"Library of Congress Control Number","url":"https://www.loc.gov/marc/bibliographic/bd010.html","repeatable":true,"indicator1":null,"indicator2":null,"subfields":{
"a":{"label":"LC control number","repeatable":true},
"b":{"label":"NUCMC control number","repeatable":false},
"z":{"label":"Canceled/invalid LC control number","repeatable":false},
"8":{"label":"Field link and sequence number","repeatable":false}}
},
...
```

**Comment by pkiraly** [comment] 2018-01-30 15:01
Good catch! It's my fault and I'll fixit asap. Meantime: 006 and 007 are repeatable, the rest are not.

**Comment by nichtich** [comment] 2018-01-30 15:18
Thanks, I adjusted the PICA Schema format accordingly so we have a common structure. Main differences:

* PICA+ does not have indicators but occurrences (additional field `occurrences`)
* PICA+ is mapped to Pica3 (additional field `pica3`)
* Subfield order can be relevant so we added a field `position` to order subfields if needed.

Example:

~~~json
{
    "tag": "021A",
    "pica3": "4000",
    "label": "Haupttitel, Titelzusatz, Verantwortlichkeitsangabe",
    "repeatable": false,
    "modified": "2017-12-18 10:41:47",
    "subfields": {
        "T": {
            "code": "T",
            "pica3": "$T",
            "label": "Feldzuordnung",
            "repeatable": false,
            "modified": "2017-08-09 07:20:11",
            "position": 1
        },
        "U": {
            "code": "U",
            "pica3": "$U...%%",
            "label": "Schriftcode",
            "repeatable": false,
            "modified": "2017-09-14 13:08:59",
            "position": 2
        },
        "a": {
            "code": "a",
            "pica3": null,
            "label": "Haupttitel",
            "repeatable": false,
            "modified": "2017-12-08 12:48:59",
            "position": 3
        },
        "d": {
            "code": "d",
            "pica3": "$d",
            "label": "Titelzusatz",
            "repeatable": false,
            "modified": "2017-08-09 07:20:11",
            "position": 5
        },
        "h": {
            "code": "h",
            "pica3": "$h",
            "label": "Verantwortlichkeitsangabe, die sich auf den Haupttitel bezieht",
            "repeatable": false,
            "modified": "2017-08-09 07:20:11",
            "position": 6
        }
    }
}
~~~

**Comment by pkiraly** [comment] 2018-01-30 16:49
@jorol: I updated the code and the output at the blog.
@nichtich: as far as I understand in MARC there is now strict order in subfileds, at least I am not aware of. My impression is that sometimes it might be important, sometime not. I never checked whether the actual records follow some order or not, maybe I should.

**Comment by phochste** [comment] 2018-01-31 06:28
The MARC standard is one thing. The content of these subfields (and ordering, and repeating of subfields) is something else. There are cataloging standards such as ISBD how these fields should be filled out (and order). But these standards have many local variations. It depends on the field if the ordering (and repetition) has semantic meaning. 
In case of the Catmandu project we must allow reading MARC fields in the order given by the catalogger, as in the order requested by the programmer.

**Comment by jorol** [comment] 2018-01-31 10:40
Thanks. I developed a Perl module and script <https://github.com/jorol/MARC-Schema> based on the schema. At the moment it only checks field tags and subfield codes. I will extend it and create a validator for Catmandu.

**Comment by pkiraly** [comment] 2018-01-31 12:30
I refactored the code a bit, and added some minor changes. The most important one that I added the code list URL and name if there is. I know one place where multiple lists are supported, but the model of the tool is not supports that (it's on my TODO list). Also sometimes the code should come from the list, sometimes it is optional (again, it's on my TODO list, not yet supported). But for you to be able to check it, I added the list name and the URL. Here is an example, see `015$2`:

```JSON
  "015": {
    "label": "National Bibliography Number",
    "url": "https://www.loc.gov/marc/bibliographic/bd015.html",
    "repeatable": true,
    "indicator1": null,
    "indicator2": null,
    "subfields": {
      "a": {
        "label": "National bibliography number",
        "repeatable": true
      },
      "q": {
        "label": "Qualifying information",
        "repeatable": true
      },
      "z": {
        "label": "Canceled/invalid national bibliography number",
        "repeatable": true
      },
      "2": {
        "label": "Source",
        "repeatable": false,
        "codelist": {
          "name": "National Bibliography Number Source Codes",
          "url": "http://www.loc.gov/standards/sourcelist/national-bibliography.html"
        }
      },
      "6": {
        "label": "Linkage",
        "repeatable": false
      },
      "8": {
        "label": "Field link and sequence number",
        "repeatable": true
      }
    }
  },
```

The code lists are available in the tool, but by default they are not exported. If you want them, you can export them with the command:

```bash
java -cp target/metadata-qa-marc-0.2-SNAPSHOT-jar-with-dependencies.jar de.gwdg.metadataqa.marc.cli.MappingToJson --with-subfield-codelists
```
Here is what you will get for the above example:

```JSON
  "015": {
    "label": "National Bibliography Number",
    "url": "https://www.loc.gov/marc/bibliographic/bd015.html",
    "repeatable": true,
    "indicator1": null,
    "indicator2": null,
    "subfields": {
      "a": {
        "label": "National bibliography number",
        "repeatable": true
      },
      "q": {
        "label": "Qualifying information",
        "repeatable": true
      },
      "z": {
        "label": "Canceled/invalid national bibliography number",
        "repeatable": true
      },
      "2": {
        "label": "Source",
        "repeatable": false,
        "codelist": {
          "name": "National Bibliography Number Source Codes",
          "url": "http://www.loc.gov/standards/sourcelist/national-bibliography.html",
          "codes": {
            "abc": {
              "label": "Anuario bibliográfico colombiano (Calí: Biblioteca Jorge García B.)"
            },
            "abd": {
              "label": "Anuario bibliográfico dominicana (Ciudad Trujillo: Biblioteca Nacional)"
            },
            "abe": {
              "label": "Anuario bibliográfico ecuatoriano (Cuenca: Banco Central del Ecuador"
            },
            "abp": {
              "label": "Anuario bibliográfico peruano (Lima: Editorial Lumen)"
            },
            "abu": {
              "label": "Anuario bibliográfico uruguayo (Montevideo: Biblioteca Nacional"
            },
            "anb": {
              "label": "Australian national bibliography (Canberra: National Library of Australia)"
            },
            "ba": {
              "label": "Bibliografía d'Andorra (Andorra La Vella: Biblioteca Nacional)"
            },
            "bbe": {
              "label": "Bibliographie de Belgique (Bruxelles: H. Manceaux)"
            },
            "bbo": {
              "label": "Bibliografía boliviana (Cochabamba: Amigos del Libro)"
            },
            "bbr": {
              "label": "Bibliografia brasileira (Rio de Janeiro: Biblioteca Nacional)"
            },
            "bc": {
              "label": "Bibliografía cubana (Habana: Biblioteca Nacional José Martá)"
            },
            "bccb": {
              "label": "Brinkman's cumulatieve catalogus van boeken (Leiden: Sijthoff)"
            },
            "bcl": {
              "label": "Bibliografía chilena (Santiago: Biblioteca Nacional de Chile)"
            },
            "be": {
              "label": "Bibliografía española (Madrid: Servicio Nacional de Información Bibliográfica)"
            },
            "bk": {
              "label": "Bulgarski knigopis (Sofiíà: Narodna biblioteka Kiril i Metodii)"
            },
            "bkck": {
              "label": "Bibliograficky katalog: Ceské knihy (Praha: Národní knihovna)"
            },
            "bksk": {
              "label": "Bibliograficky katalog: Slovenské knihy (Brastislava: Národní knihovna"
            },
            "bl": {
              "label": "Bibliographie luxembourgeoise pour l'année (Luxembourg: Bibliothèque nationale)"
            },
            "bm": {
              "label": "Bibliografía mexicana (Ciudad de México: Biblioteca Nacional)"
            },
            "bnb": {
              "label": "British national bibliography (London: British Library, Bibliographic Services Division)"
            },
            "bnc": {
              "label": "Bibliografia nacional de Catalunya (Barcelona: Departement de Cultura de la Generalitat de Catalunya)"
            },
            "bne": {
              "label": "Bibliografía nacional de España (Madrid: Biblioteca Nacional de España)"
            },
            "bnf": {
              "label": "Bibliographie nationale française (Paris: Bibliothèque nationale de France)"
            },
            "bni": {
              "label": "Bibliografia nazionale italiana (Roma: Istituto centrale per il catalogo unico delle biblioteche italiane e per le informazioni)"
            },
            "bnm": {
              "label": "Bibljografija nazzjonal ta' Malta = National bibliography of Malta (Valletta: National Library of Malta)"
            },
            "bnr": {
              "label": "Bibliografia nationala româna (Bucuresti: Biblioteca Nationale a României)"
            },
            "bv": {
              "label": "Bibliografía venezolana (Caracas: Instituto Autónomo Biblioteca Nacional y Servicios de Bibliotecas)"
            },
            "can": {
              "label": "Canadiana (Ottawa: National Library of Canada)"
            },
            "cncr": {
              "label": "Catálogo nacional de Costa Rica (San José: Biblioteca Nacional)"
            },
            "db": {
              "label": "Deutsche Bibliographie (Frankfurt am Main: Die Deutsche Bibliothek)"
            },
            "dbf": {
              "label": "Dansk bogfortegnelse (Ballerup: Dansk Bibliotekscenter)"
            },
            "dnb": {
              "label": "Deutsche Nationalbibliografie External Link"
            },
            "eev": {
              "label": "Ellenikê ethnikê vivliografia (Athenai: Ethnikê Vivliothêkê tês Ellados)"
            },
            "hb": {
              "label": "Hrvatska bibliografija (Zagreb: Nacionalna i sveucilisna biblioteka)"
            },
            "ib": {
              "label": "Islensk bókaskrá (Reykjevík: Landbókasafn Islands - Háskólabókasafn)"
            },
            "ipr": {
              "label": "Irish publishing record (Dublin: University College of Dublin)"
            },
            "jnb": {
              "label": "Japanese National Bibliography (Tokyo: National Diet Library)"
            },
            "kktzm": {
              "label": "Kokuritsu kokkai Toshokan zosho mokuroku (Tokyo: National Diet Library)"
            },
            "kl": {
              "label": "Knizhnaíà letopis' (Moskva: Rossiiskaíà knizhnaíà palata)"
            },
            "la": {
              "label": "Libros argentinos (Buenos Aires: Cámara Argentina del Libro)"
            },
            "lb": {
              "label": "Liechtensteinische Bibliographie (Vaduz: Liechtensteinische Landesbibliothek)"
            },
            "ldb": {
              "label": "Letapis Druku Belarusi = Chronicle of the Press Belarus (Minsk: Natsyianal'naia kniznaia palata Belarusi)"
            },
            "mnb": {
              "label": "Magyar nemzeti bibliográfia (Budapest: Országos Széchényi Könyvtár)"
            },
            "nbf": {
              "label": "Norsk bokfortegnelse (Oslo: Norske bokhandlerforening)"
            },
            "nznb": {
              "label": "New Zealand national bibliography (Wellington: National Library of New Zealand)"
            },
            "oeb": {
              "label": "Oesterreichische Bibliographie (Wien: Oesterreichische Nationalbibliothek)"
            },
            "pb": {
              "label": "Przewodnik bibliograficzny (Warszawa: Biblioteka Narodowa)"
            },
            "sanb": {
              "label": "South African national bibliography (Pretoria: National Library of South Africa)"
            },
            "sbf": {
              "label": "Svensk bokförteckning (Stockholm: Svenska bokhandlareforeningen)"
            },
            "skl": {
              "label": "Suomen kirjallisuus (Helsinki: Helsingin Yliopiston Kirjasto)"
            },
            "slb": {
              "label": "Slovenska bibliografija (Ljubljana: Narodna in univerzitetna knjiznica)"
            },
            "szb": {
              "label": "Das Schweizer Buch: Schweizerische Nationalbibliographie (Zürich: Schweizerischer Buchhändler- und Verlegerverband)"
            },
            "tnb": {
              "label": "Taiwan National Bibliography (Taipei: National Central Library)"
            },
            "ulk": {
              "label": "Ukraïna: litopys knih (Kyïv: Knyzhkova palata Ukraïny)"
            },
            "znb": {
              "label": "Zimbabwe national bibliography (Harare: National Archives"
            }
          }
        }
      },
      "6": {
        "label": "Linkage",
        "repeatable": false
      },
      "8": {
        "label": "Field link and sequence number",
        "repeatable": true
      }
    }
  },
```

There is one exception: MARC Organization Codes at http://www.loc.gov/marc/organizations/orgshome.html. This is not a downloadable list, just pointers to another lists. I found only one list downloadable, the German-language countries (Germany, Scwitzerland and Austria) organizational codes. I never was able to access the Canadian website. I've collected some individual codes from the Library of Congress and OCLC's websites, but only occasionally. It is not incorporated into the schema export, but it is available as a distinct file at https://github.com/pkiraly/metadata-qa-marc/blob/33e0c30f2a584445611bebbb59718d3be9f85fe6/src/main/resources/marc/organization-codes.csv.

**Comment by nichtich** [comment] 2018-01-31 14:29
I've implemented **Catmandu::Validator::PICA** in [Catmandu::PICA](https://github.com/gbv/Catmandu-PICA) (in the `dev` branch, not released yet). The final form of schema files is not settled yet, maybe we should create a JSON Schema for MARC and PICA Schemas?

We think to prepend each subfield with a `$` because JSON object key `"0"` causes problems in PHP, so better use`$0` instead.

Moreover both fields and subfield could be described with a boolean flag `"required"` to check whether mandatory fields are present.

**Comment by pkiraly** [comment] 2018-02-01 08:20
Huh, I think, that at this point we should somehow involve a real MARC21 expert [1], because these questions are over my knowledge.

* JSON schema: you mean JSON-LD?
* for `$`: I am not a big fan of adding some formatting helper because of a particular technology. I would suggest instead not use the codes as a key in an associative array, but use a list of associative arrays, where the code is a value:

```
[
  {
    "code": "6",
    "label": "Linkage",
    "repeatable": false
  },
]
```
instead of
```
{
      "6": {
        "label": "Linkage",
        "repeatable": false
      },
}
```
Is that acceptable for you?

* `"required"` - I haven't found any required field in MARC21, maybe it is governed on ISBD or AACR2 level.

[1] Do you know a MARC expert? Maybe Karen Coyle? Or we can ask a question in the Code4Lib mailing list.

**Comment by jorol** [comment] 2018-02-01 09:39
>  I am not a big fan of adding some formatting helper because of a particular technology.

I would also not prepend another character to the codes. 

>  associative array, but use a list of associative arrays

I really prefer the associative array/hash structure, because you can use them quiet easy as "lookup tables".

**Comment by nichtich** [comment] 2018-02-01 13:33
There is no MARC21 but only dialects and applications of MARC21 which should be described by individual MARC Schemas.  I started [a more detailed description of schema format](https://github.com/gbv/PicaHelpRest/wiki/Schema) (as text instead of [JSON Schema](http://json-schema.org/)). @jorol is right, good to discuss this here! I'd wait for asking MARC experts until we have a common document to present. We should not try to include every single aspect of MARC but what can be expressed formally.

**Comment by cKlee** [comment] 2018-02-13 10:31
Is there a reason why positions are always two digits (00 .. 09) other than the order of positions in a JSON file? To check validity of field entries, one must extract data at position/range. This can be made more easily if positions don't have leading zeros. Otherwise one must strip leading zeros first.

**Comment by cKlee** [comment] 2018-02-15 09:41
@pkiraly will you update your [MARC21-in-Json example](http://pkiraly.github.io/2018/01/28/marc21-in-json/) in respect to the [Avram Schema](https://format.gbv.de/schema/avram)?

Your example uses JSON arrays as values for positions, codes and types, while Avram uses JSON objects.

**Comment by pkiraly** [comment] 2018-02-15 10:12
@cKlee Yes, I'll update it. Monday we had a personal meeting with Jakob to discuss Avram, but since then I did not had time to update the output. I'll notify your when it's done.

**Comment by nichtich** [comment] 2018-02-21 13:25
I have extended the specification of Avram and created a JSON Schema to check Avram files against the specification:

* http://format.gbv.de/schema/avram/specification
* https://format.gbv.de/schema/avram/schema.json

**Comment by pkiraly** [comment] 2018-02-25 09:40
Dear @nichtich and @cKlee,

is there a validator to check that the exported JSON fits for Avram?

Best,
Péter

**Comment by pkiraly** [comment] 2018-02-25 09:57
I update the output, which is now available at https://raw.githubusercontent.com/pkiraly/metadata-qa-marc/master/src/main/resources/marc-schema.json.
If I'll figure it out how to validate it, I fix the errors (if there are any).

**Comment by pkiraly** [comment] 2018-02-25 12:36
I found an online validator (https://www.jsonschemavalidator.net/) and I fixed some issues reported by this tool.

**Comment by cKlee** [comment] 2018-03-05 09:25
From field 001 until 007 you are using labels as values for the key 'tag'. E.g.

```
"007": {
      "tag": "PhysicalDescription",
      "label": "Physical Description",
      "repeatable": true,
[...]
```

**Comment by pkiraly** [comment] 2018-03-05 20:27
@cKlee Thanks, you are absolutely right, it is an issue. I fixed it.

**Comment by arturisimo** [comment] 2020-04-30 13:46
nice work.. @pkiraly!.... there is somewhere json schema for marc21 for **authority data**?

**Comment by pkiraly** [comment] 2020-04-30 14:03
@arturisimo Thanks! I am not aware of any work on JSON schema of MARC authority.

**Comment by timathom** [comment] 2023-10-21 14:42
@arturisimo You can find a similar approach for the Authority and Holdings Formats here: https://github.com/timathom/marc-schema. I hope to align this with @pkiraly's work in the future.

**Comment by timathom** [comment] 2023-10-21 15:39
@pkiraly It's a bit of a corner case, but for completeness, you might consider adding fixed-length values ("static values") to your definition for certain subfields, such as [533$7](https://github.com/timathom/marc-schema/blob/837ea61ab9b2fe176cb3d4e1ec9188266f043b35/marc21_json_schema.json#L21748).

**Comment by pkiraly** [comment] 2023-10-23 16:07
> @pkiraly It's a bit of a corner case, but for completeness, you might consider adding fixed-length values ("static values") to your definition for applicable subfields, such as [533$7](https://github.com/timathom/marc-schema/blob/837ea61ab9b2fe176cb3d4e1ec9188266f043b35/marc21_json_schema.json#L21748).

You are right. I have just modified the export functionalities to include these positions, such as:

```json
{
   "tag":"533",
   "label":"Reproduction Note",
   "url":"https:\/\/www.loc.gov\/marc\/bibliographic\/bd533.html",
   "repeatable":true,
   "indicator1":null,
   "indicator2":null,
   "subfields":{
      "a":{
         "label":"Type of reproduction",
         "repeatable":false
      },
      ...
      "5":{
         "label":"Institution to which field applies",
         "repeatable":false
      },
      "7":{
         "label":"Fixed-length data elements of reproduction",
         "repeatable":false,
         "positions":{
            "00":{
               "label":"Type of date\/Publication status",
               "repeatable":false,
               "start":0,
               "end":1
            },
            "01-04":{
               "label":"Date 1",
               "repeatable":false,
               "start":1,
               "end":5
            },
            "05-08":{
               "label":"Date 2",
               "repeatable":false,
               "start":5,
               "end":9
            },
            "09-11":{
               "label":"Place of publication, production, or execution",
               "repeatable":false,
               "start":9,
               "end":12
            },
            "11-12":{
               "label":"Frequency",
               "repeatable":true,
               "start":11,
               "end":13,
               "unitLength":1,
               "codes":[
                  {
                     "code":" ",
                     "label":"No determinable frequency"
                  },
                  {
                     "code":"a",
                     "label":"Annual"
                  },
                  {
                     "code":"b",
                     "label":"Bimonthly"
                  },
                  {
                     "code":"c",
                     "label":"Semiweekly"
                  },
                  {
                     "code":"d",
                     "label":"Daily"
                  },
                  {
                     "code":"e",
                     "label":"Biweekly"
                  },
                  {
                     "code":"f",
                     "label":"Semiannual"
                  },
                  {
                     "code":"g",
                     "label":"Biennial"
                  },
                  {
                     "code":"h",
                     "label":"Triennial"
                  },
                  {
                     "code":"i",
                     "label":"Three times a week"
                  },
                  {
                     "code":"j",
                     "label":"Three times a month"
                  },
                  {
                     "code":"k",
                     "label":"Continuously updated"
                  },
                  {
                     "code":"n",
                     "label":"Not applicable"
                  },
                  {
                     "code":"m",
                     "label":"Monthly"
                  },
                  {
                     "code":"q",
                     "label":"Quarterly"
                  },
                  {
                     "code":"s",
                     "label":"Semimonthly"
                  },
                  {
                     "code":"t",
                     "label":"Three times a year"
                  },
                  {
                     "code":"u",
                     "label":"Unknown"
                  },
                  {
                     "code":"w",
                     "label":"Weekly"
                  },
                  {
                     "code":"z",
                     "label":"Other frequencies"
                  }
               ]
            },
            "13":{
               "label":"Regularity",
               "repeatable":false,
               "start":13,
               "end":14,
               "codes":[
                  {
                     "code":" ",
                     "label":"Not applicable"
                  },
                  {
                     "code":"x",
                     "label":"Completely irregular"
                  },
                  {
                     "code":"n",
                     "label":"Normalized irregular"
                  },
                  {
                     "code":"r",
                     "label":"Regular"
                  },
                  {
                     "code":"u",
                     "label":"Unknown"
                  }
               ]
            },
            "14":{
               "label":"Form of item",
               "repeatable":false,
               "start":14,
               "end":15
            }
         }
      },
      "6":{
         "label":"Linkage",
         "repeatable":false
      },
      "8":{
         "label":"Field link and sequence number",
         "repeatable":true
      }
   }
}
```

The files are available at https://github.com/pkiraly/qa-catalogue/tree/main/marc-schema

Any other suggestions would be welcome!

**Comment by nichtich** [comment] 2023-10-24 07:57
I've summarized differences of Tim's approach to Avram specification at https://github.com/timathom/marc-schema/issues/1. You both included `start` and in [positions](https://format.gbv.de/schema/avram/specification#positions) and 
`end` or `stop` respectively. This is not supported in Avram as the values are implied by object key:

~~~json
{
           "00":{
               "label":"...",
               "start":0,                           // not in Avram 
               "stop":0                             // not in Avram
            },
            "01-04":{
               "label":"Date 1",
               "start":1,                           // not in Avram 
               "end":5                              // not in Avram
            }
}
~~~

Shall `start` and `end` or (`start` and another key) added as optional keys to the specification? There are already other implied keys such as `tag` and `occurrence` deriveable from object keys.

 If so, I'd prefer inclusive value  `end`, e.g. `01-04` (second to fifth character) having `"start":1,"end":4`.

**Comment by pkiraly** [comment] 2023-10-24 08:14
@nichtich Yes, it would be great. Some thoughts:

* there are two kinds of positional data elements in MARC: control fields - where the whole field is positional, and in subfields of data fields.
* it is a rarely used feature in data element's subfield, so there it should be optional
* sometimes the code is shorter (e.g. 1 character) than the available space (e.g. 4 character), so I suggest two additional features: `unitlength` or `codelength` referring to the length of the code, and `repeatable` denoting if there might be multiple codes in the available positions.

**Comment by nichtich** [comment] 2023-10-24 15:06
@pkiraly can you give an example of short code for longer space? Are there examples of these where a code is *not* repeatable?

**Comment by timathom** [comment] 2023-10-24 15:06
@nichtich, Yes, I'd also prefer explicit `start` and `end` values, as suggested.

The two "control subfields" that @pkiraly refers to are `$w` (in the MARC Authority Format) and `$7` (in the MARC Bibliographic Format). These are always called "Control subfield" except in [533$7](https://www.loc.gov/marc/bibliographic/bd533.html), where it's called "Fixed-length data elements of reproduction."

The MARC Authority Format makes extensive use of `$w` to record a 4-position sequence of coded values (see [the description here](https://www.loc.gov/marc/authority/adtracing.html)). In this case, all positions are typically filled (see, e.g., the first 400 field in [this record](https://id.loc.gov/authorities/names/nr2003009939.marcxml.xml)).

For `$7` in the Bibliographic Format (in the context of Linking Entry fields), [the documentation](https://www.loc.gov/marc/bibliographic/bd760787.html) says this:

> Up to four character positions (designated 0, 1, etc.) that indicate special characteristics of the linked entry. Because the definitions of the codes in subfield $7 are dependent on the character position in which they occur, the coding of any character position mandates that each preceding character position contains a code or the fill character (|); succeeding character positions need not be used. For example, if position 0 and 1 are not applicable but position 2 is applicable, then position 0 and 1 contain code n (Not applicable) or a fill character.

For `533$7`, the documentation says:

> All character positions must contain either a defined code or a fill character (|)

So, I'm not sure that `unitlength` and `repeatable` are necessary? But maybe positions following position 0 in the Linking Entry `$7` could be flagged with an `optional` (boolean) key? 

@pkiraly, I see that your current representation of 533$7 has an overlap for position 11, but I don't see that possibility in [the documentation](https://www.loc.gov/marc/bibliographic/bd533.html).

**Comment by timathom** [comment] 2023-10-24 19:37
Other "control subfields": https://www.loc.gov/marc/bibliographic/ecbdcntf.html (`$6` and `$8` are particularly tricky).

**Comment by nichtich** [comment] 2023-10-26 14:29
I'll add explicit `start` and `end` to the specification.

Currrent schema files [in this repository](https://github.com/pkiraly/qa-catalogue/tree/main/marc-schema) don't include `codelength` or `unitlength`, so I assume we don't need them.

Control subfields `$6` and `$8` can partly be modeled with `pattern` (a regular expression) but these seem not to be supported by qa-catalogue yet. Several more subfields could be specified with regular expressions but the MARC21 specification does not officially provide such patterns. More details about parts of a pattern such as "Field link type" in `$8` could be expressed by combination of `pattern` and a to-be-introduced `groups` key to define value of regex capturing groups. But I doubt we want to go this deep by now.

**Comment by pkiraly** [comment] 2023-10-26 15:45
Here is an example for `repeatableContent` and `unitLength` (from a control field):

```json
"006":{
  "tag":"006",
  "label":"Additional Material Characteristics",
  "repeatable":true,
  "types":{
    "All Materials":{...},
    "Books":{
      "positions":{
        "01-04":{
          "label":"Illustrations",
          "url":"https:\/\/www.loc.gov\/marc\/bibliographic\/bd006.html",
          "start":1,
          "end":5,
          "repeatableContent":true,                   ← repeatableContent
          "unitLength":1,                             ← unitLength
          "codes":{
            " ":{"label":"No illustrations"},
            "a":{"label":"Illustrations"},
            "b":{"label":"Maps"},
            "c":{"label":"Portraits"},
            ...
          }
        },
```

Most of the cases the length of individual codes are 1 character long, so unitLength might be an optional field with default value 1. It could be calculated from the lengh of the first code, but I prefer explicit schema.

**Comment by pkiraly** [comment] 2023-10-26 15:51
Regarding to regex: we have regex in Java (and they play a role in validation), but it seems that they are not exported - my fault. I'll create a ticket for that.

**Comment by nichtich** [comment] 2023-10-27 08:33
I've release Avram specification version 0.9.0 with additional keys `start` and `end`. I'd like to fix version 1.0 in early 2024 and the exported JSON structure of qa-catalogue should then conform to Avram (or export of schemes in qa-catalogue should contain a post-processing step to reduce JSON Schemas to valid Avram). Comparing current specification 0.9.0 with exported JSON I found additional non-specified features. These could be added to Avram specification or removed from JSON Schema:

- field `types` (these were part of Avram but removed with 0.8.0 because it complicates validation)
- `historical-subfields` `historical-codes` (same for these under name `deprecated-subfields` and `deprecated-codes`, may be added back with key `deprecated: true` instead?)
- `repeatableContent` and `unitLength` (see above)

There may be additional features of validation in Java to be encoded in JSON but the latter will always be a subset of the former to be usable.

**Comment by pkiraly** [comment] 2023-10-27 09:00
What about if we would create two versions: one Avram compatible, and one with the extras? `types` are very important, because otherwise the control fields are not interpretable correctly. In PICA there are no control fields at all, and I haven't found a similar solution for problems so far in PICA, but it MARC21 they are there in  every records.
Historical data elements/values and repeatability are less important, the later moreover can be figured it out implicitly given the start, end and the length of the codes.
For historical data elements the `deprecated: true` flag would be a solution.

**Comment by nichtich** [comment] 2023-10-27 09:21
It appears that `unitLength` if given is always `1` and it only exists when `repeatableContent` is `true` (except for position `11-12` *Frequency* of subfield `$7` in [533](https://www.loc.gov/marc/bibliographic/bd533.html), this seems to be an error as the correct position is `12` instead of `11-12`). So the key `unitLength` seems to be redundant.

There are 16 cases of `repeatableContent` being `true`. An example is [008/24-27 - Nature of contents (=006/07-10)](https://www.loc.gov/marc/bibliographic/bd008b.html):

> Up to four one-character codes that indicate whether a significant part of the item is or contains certain types of material. If fewer than four codes are assigned, the codes are left justified and unused positions contain blanks (#).

Avram allows to reference [codelist](https://format.gbv.de/schema/avram/specification#codelist) to avoid repeating the same list of codes in multiple places (e.g. field 006 and field 008), so this would be the intended way to express the schema in Avram without `unitLength` and `repeatableContent`:

~~~json
  # root key of the schema
  "codelists": {
     "https://www.loc.gov/marc/bibliographic/bd008b.html#nature-of-contents" : {
        " ": {
          "label": "No specified nature of contents"
        },
        "a": {
          "label": "Abstracts/summaries"
        },
        "b": {
          "label": "Bibliographies"
        },
        ...

    # as part of field 006
    "07-10": {
        "label": "Nature of contents",
        "url": "https://www.loc.gov/marc/bibliographic/bd006.html",
        "start": 7,
        "end": 10,
        "positions": {
          "0": { "codes": "https://www.loc.gov/marc/bibliographic/bd008b.html#nature-of-contents" },
          "1": { "codes": "https://www.loc.gov/marc/bibliographic/bd008b.html#nature-of-contents" },
          "2": { "codes": "https://www.loc.gov/marc/bibliographic/bd008b.html#nature-of-contents" },
          "3": { "codes": "https://www.loc.gov/marc/bibliographic/bd008b.html#nature-of-contents" }
         }
    }     
    
    # as part of field 008
    "24-27": {
        "label": "Nature of contents",
        "url": "https://www.loc.gov/marc/bibliographic/bd008b.html",
        "start": 24,
        "end": 27,
        "positions": {
          "0": { "codes": "https://www.loc.gov/marc/bibliographic/bd008b.html#nature-of-contents" },
          "1": { "codes": "https://www.loc.gov/marc/bibliographic/bd008b.html#nature-of-contents" },
          "2": { "codes": "https://www.loc.gov/marc/bibliographic/bd008b.html#nature-of-contents" },
          "3": { "codes": "https://www.loc.gov/marc/bibliographic/bd008b.html#nature-of-contents" }
         }
    }
~~~

**Comment by pkiraly** [comment] 2023-10-27 10:01
To reorganize the code lists is an old debt on my side... it is good time to do it.

**Comment by nichtich** [comment] 2024-04-04 11:49
Five years in the making but this is done and checked! :-)

**Closed by nichtich** 2024-04-04 11:49 UTC
Labels: avram
